// Do not modify this file, it was generated by @npc/cli
import { createIconComponent } from "./__create__";

export const SRC_ICON_BACK = "/icon/back.svg";

export const IconBack = createIconComponent("IconBack", SRC_ICON_BACK);
