// Do not modify this file, it was generated by @npc/cli
import { createIconComponent } from "./__create__";

export const SRC_ICON_CLOSE = "/icon/close.svg";

export const IconClose = createIconComponent("IconClose", SRC_ICON_CLOSE);
