// Do not modify this file, it was generated by @npc/cli
import { createIconComponent } from "./__create__";

export const SRC_ICON_EDIT = "/icon/edit.svg";

export const IconEdit = createIconComponent("IconEdit", SRC_ICON_EDIT);
