// Do not modify this file, it was generated by @npc/cli
import { createIconComponent } from "./__create__";

export const SRC_ICON_INFO = "/icon/info.svg";

export const IconInfo = createIconComponent("IconInfo", SRC_ICON_INFO);
