// Do not modify this file, it was generated by @npc/cli
import { createIconComponent } from "./__create__";

export const SRC_ICON_PLUS = "/icon/plus.svg";

export const IconPlus = createIconComponent("IconPlus", SRC_ICON_PLUS);
