// Do not modify this file, it was generated by @npc/cli
import { createIconComponent } from "./__create__";

export const SRC_ICON_PREVIEW = "/icon/preview.svg";

export const IconPreview = createIconComponent("IconPreview", SRC_ICON_PREVIEW);
