// Do not modify this file, it was generated by @npc/cli
import { createIconComponent } from "./__create__";

export const SRC_ICON_SAVE = "/icon/save.svg";

export const IconSave = createIconComponent("IconSave", SRC_ICON_SAVE);
