// Do not modify this file, it was generated by @npc/cli
import { createIconComponent } from "./__create__";

export const SRC_ICON_SEARCH = "/icon/search.svg";

export const IconSearch = createIconComponent("IconSearch", SRC_ICON_SEARCH);
