// Do not modify this file, it was generated by @npc/cli
import { createIconComponent } from "./__create__";

export const SRC_ICON_TRASH = "/icon/trash.svg";

export const IconTrash = createIconComponent("IconTrash", SRC_ICON_TRASH);
