// Do not modify this file, it was generated by @npc/cli
import { createIconComponent } from "./__create__";

export const SRC_ICON_WARN = "/icon/warn.svg";

export const IconWarn = createIconComponent("IconWarn", SRC_ICON_WARN);
