

FROM node:18-alpine AS base

ARG argName
ENV argName=${argName}

RUN npm i http-server -g

RUN echo ${argName} >> /test.arg

FROM base as installer

# Set working directory
WORKDIR /app
COPY . .

RUN npm i pnpm -g && pnpm install

CMD http-server