// Do not modify this file, it was generated by @npcs/cli

import _ImageFirstNote from "@assets/image/first-note.svg";
import { FC, SVGProps } from "react";

export const ImageFirstNote = _ImageFirstNote as FC<
  SVGProps<SVGElement> & { hidden?: boolean }
>;
