// Do not modify this file, it was generated by @npc/cli

import _ImageNotFound from "@assets/image/not-found.svg";
import { FC, SVGProps } from "react";

export const ImageNotFound = _ImageNotFound as FC<
  SVGProps<SVGElement> & { hidden?: boolean }
>;
