// Do not modify this file, it was generated by @npc/cli
import { createImageComponent } from "./__create__";

export const SRC_IMAGE_FIRST_NOTE = "/image/first-note.svg";

const displayName = "ImageFirstNote";
export const ImageFirstNote = createImageComponent(
  displayName,
  SRC_IMAGE_FIRST_NOTE,
);
