// Do not modify this file, it was generated by @npc/cli

import _IconBack from "@assets/icon/back.svg"
import { FC, SVGProps } from "react"

export const IconBack = _IconBack as FC<SVGProps<SVGElement> & { hidden?: boolean }>
