// Do not modify this file, it was generated by @npc/cli

import _IconClose from "@assets/icon/close.svg"
import { FC, SVGProps } from "react"

export const IconClose = _IconClose as FC<SVGProps<SVGElement> & { hidden?: boolean }>
