// Do not modify this file, it was generated by @npc/cli

import _IconEdit from "@assets/icon/edit.svg";
import { FC, SVGProps } from "react";

export const IconEdit = _IconEdit as FC<
  SVGProps<SVGElement> & { hidden?: boolean }
>;
