// Do not modify this file, it was generated by @npc/cli

import _IconInfo from "@assets/icon/info.svg"
import { FC, SVGProps } from "react"

export const IconInfo = _IconInfo as FC<SVGProps<SVGElement> & { hidden?: boolean }>
