// Do not modify this file, it was generated by @npc/cli

import _IconPlus from "@assets/icon/plus.svg"
import { FC, SVGProps } from "react"

export const IconPlus = _IconPlus as FC<SVGProps<SVGElement> & { hidden?: boolean }>
