// Do not modify this file, it was generated by @npcs/cli

import _IconPlus from "@assets/icon/plus.svg";
import { FC, SVGProps } from "react";

export const IconPlus = _IconPlus as FC<
  SVGProps<SVGElement> & { hidden?: boolean }
>;
