// Do not modify this file, it was generated by @npc/cli

import _IconPreview from "@assets/icon/preview.svg"
import { FC, SVGProps } from "react"

export const IconPreview = _IconPreview as FC<SVGProps<SVGElement> & { hidden?: boolean }>
