// Do not modify this file, it was generated by @npcs/cli

import _IconSave from "@assets/icon/save.svg";
import { FC, SVGProps } from "react";

export const IconSave = _IconSave as FC<
  SVGProps<SVGElement> & { hidden?: boolean }
>;
