// Do not modify this file, it was generated by @npcs/cli

import _IconSearch from "@assets/icon/search.svg";
import { FC, SVGProps } from "react";

export const IconSearch = _IconSearch as FC<
  SVGProps<SVGElement> & { hidden?: boolean }
>;
