// Do not modify this file, it was generated by @npcs/cli

import _IconTrash from "@assets/icon/trash.svg";
import { FC, SVGProps } from "react";

export const IconTrash = _IconTrash as FC<
  SVGProps<SVGElement> & { hidden?: boolean }
>;
