// Do not modify this file, it was generated by @npcs/cli

import _IconWarn from "@assets/icon/warn.svg";
import { FC, SVGProps } from "react";

export const IconWarn = _IconWarn as FC<
  SVGProps<SVGElement> & { hidden?: boolean }
>;
